ocrDictionnary = [
    {"correction": "Out 1 Stereo", "list": ["out1st", "oui1st", "ou!1st"]},
    {"correction": "Out 2 Stereo", "list": ["out2st", "oui2st", "ou!2st"]},
    {"correction": "Out 3 Stereo", "list": ["out3st", "oui3st", "ou!3st"]},
    {"correction": "Out 4 Stereo", "list": ["out4st", "oui4st", "ou!4st"]},
    {"correction": "Out 5 Stereo", "list": ["out5st", "oui5st", "ou!5st"]},
    {"correction": "Out 6 Stereo", "list": ["out6st", "oui6st", "ou!6st"]},
    {"correction": "Out 7 Stereo", "list": ["out7st", "oui7st", "ou!7st"]},
    {"correction": "Out 8 Stereo", "list": ["out8st", "oui8st", "ou!8st"]},
    {"correction": "Out 9 Stereo", "list": ["out9st", "oui9st", "ou!9st"]},
    {"correction": "Out 10 Stereo", "list": ["out10st", "oui10st", "ou!10st"]},
    {"correction": "Out 11 Stereo", "list": ["out11st", "oui11st", "ou!11st"]},
    {"correction": "Out 12 Stereo", "list": ["out12st", "oui12st", "ou!12st"]},
    {"correction": "Out 13 Stereo", "list": ["out13st", "oui13st", "ou!13st"]},
    {"correction": "Out 14 Stereo", "list": ["out14st", "oui14st", "ou!14st"]},
    {"correction": "Out 15 Stereo", "list": ["out15st", "oui15st", "ou!15st"]},
    {"correction": "Out 16 Stereo", "list": ["out16st", "oui16st", "ou!16st"]},
    {"correction": "Out 17 Mono", "list": ["out17mn", "oui17mn", "ou!17mn"]},
    {"correction": "Out 18 Mono", "list": ["out18mn", "oui18mn", "ou!18mn"]},
    {"correction": "Out 19 Mono", "list": ["out19mn", "oui19mn", "ou!19mn"]},
    {"correction": "Out 20 Mono", "list": ["out20mn", "oui20mn", "ou!20mn"]},
    {"correction": "Out 21 Mono", "list": ["out21mn", "oui21mn", "ou!21mn"]},
    {"correction": "Out 22 Mono", "list": ["out22mn", "oui22mn", "ou!22mn"]},
    {"correction": "Out 23 Mono", "list": ["out23mn", "oui23mn", "ou!23mn"]},
    {"correction": "Out 24 Mono", "list": ["out24mn", "oui24mn", "ou!24mn"]},
    {"correction": "Out 25 Mono", "list": ["out25mn", "oui25mn", "ou!25mn"]},
    {"correction": "Out 26 Mono", "list": ["out26mn", "oui26mn", "ou!26mn"]},
    {"correction": "Out 27 Mono", "list": ["out27mn", "oui27mn", "ou!27mn"]},
    {"correction": "Out 28 Mono", "list": ["out28mn", "oui28mn", "ou!28mn"]},
    {"correction": "Out 29 Mono", "list": ["out29mn", "oui29mn", "ou!29mn"]},
    {"correction": "Out 30 Mono", "list": ["out30mn", "oui30mn", "ou!30mn"]},
    {"correction": "Out 31 Mono", "list": ["out31mn", "oui10mn", "ou!31mn"]},
    {"correction": "Out 32 Mono", "list": ["out32mn", "oui32mn", "ou!32mn"]},
    {"correction": "OverHead", "list": ["oh.ssd5"]},
    {"correction": "Room", "list": ["room.ssd5", "rooitlssd5", ""]},
    {"correction": "Room B", "list": ["roomb.ssd5"]},
    {"correction": "SLR", "list": ["slr.ssd5"]}
]
