routingMenu36 = [
    "Out 1 Stereo",
    "Out 2 Stereo",
    "Out 3 Stereo",
    "Out 4 Stereo",
    "Out 5 Stereo",
    "Out 6 Stereo",
    "Out 7 Stereo",
    "Out 8 Stereo",
    "Out 9 Stereo",
    "Out 10 Stereo",
    "Out 11 Stereo",
    "Out 12 Stereo",
    "Out 13 Stereo",
    "Out 14 Stereo",
    "Out 15 Stereo",
    "Out 16 Stereo",
    "Out 17 Mono",
    "Out 18 Mono",
    "Out 19 Mono",
    "Out 20 Mono",
    "Out 21 Mono",
    "Out 22 Mono",
    "Out 23 Mono",
    "Out 24 Mono",
    "Out 25 Mono",
    "Out 26 Mono",
    "Out 27 Mono",
    "Out 28 Mono",
    "Out 29 Mono",
    "Out 30 Mono",
    "Out 31 Mono",
    "Out 32 Mono",
    "OverHead",
    "Room",
    "Room B",
    "SLR"
]
